config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :rooms do
    get 'allocate_repetitive', to: 'rooms#allocate_repetitive'
    get 'allocate_non_repetitive', to: 'rooms#allocate_non_repetitive'
    post 'allocate/repetitive_event', to: 'rooms#allocate_repetitive_event'
    post 'allocate/non_repetitive_event', to: 'rooms#allocate_non_repetitive_event'
  end

  resources :events do
    get 'search', to: 'events#search', on: :collection
    get 'cancel', to: 'events#cancel', on: :member
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @room_types = Room.types
    @days_of_week = {1 => 'Segunda', 2 => 'Terça', 3 => 'Quarta', 4 => 'Quinta', 5 => 'Sexta'}
  end
end

app/views/home/index.html.erb
   <center>
  <br>
  <%= image_tag("classroom.png", :alt => "classroom") %>
  <h2>Alocador de salas</h2>
</center>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <h3> Buscar sala disponível </h3>
    <hr>
    <%= form_tag rooms_path, :method => "get" , id: "search-available-rooms-form" do%>

      <%= label_tag(:event_type, "Tipo do Evento") %>
      <%= select_tag(:event_type_id,options_for_select([['Não Repetitivo', 1], ['Repetitivo', 2]]), {class: 'form-control', id: 'event_type_select'}) %>

      <br><br>
      <%= label_tag(:room_type, "Tipo de Sala") %>
      <%= select_tag(:room_type_class, options_for_select(@room_types.invert.to_a), {class: 'form-control'})%>

      <br><br>
      <%= label_tag(:capacity, "Capacidade") %>
      <%= number_field_tag(:capacity, params[:capacity], in: 1..400, step: 1) %>

      <br><br>
      <%= label_tag(:date, "Data do Evento") %>

      <div id="not_repetitive_date" style="display: inline;">
        <input type='text' class="form-control" id='days' name="days"/>
      </div>

      <div id="repetitive_date" style="display: none;">
        <% @days_of_week.each do |id, day| %>
          <%= check_box_tag "days_of_week[]", id %>
          <%= day %>
        <% end%>
      </div>
      <br><br>
      <div class="row">
        <div class="col-lg-6">
          <%= label_tag(:hour, "Hora inicial") %>
          <div class="input-group bootstrap-timepicker timepicker">
            <input id="start_time" name="start_time" type="text" class="form-control input-small" placeholder="Hora inicial">
            <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
          </div>
        </div>
        <div class="col-lg-6">
          <%= label_tag(:hour, "Hora final") %>
          <div class="input-group bootstrap-timepicker timepicker">
            <input id="end_time" name="end_time" type="text" class="form-control input-small" placeholder="Hora final">
            <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
          </div>
        </div>
      </div>
      <br><br>
    <div id="search_btn" class="pull-right">
      <%= submit_tag "Buscar", :name => nil, :class => "btn btn-primary"%>
    </div>
  <% end %>
  </div>
</div>
<br>

<script type="text/javascript">

  $(document).ready(function(){
    var options = {
      maxHours: 24,
      showMeridian: false,
      minuteStep: 60,
      defaultTime: false,
      icons: {
        up: 'fa fa-chevron-up',
        down: 'fa fa-chevron-down'
      }
    };
    $('#start_time').timepicker(options);
    $('#end_time').timepicker(options);
    $('#days').datepicker({
      multidate: true,
      language: 'pt'
    });

    $("#event_type_select").on("click", function() {
      if($("#event_type_select").val() == 2){
        $("#not_repetitive_date").hide();
        $("#repetitive_date").show();
      }
      else{
        $("#repetitive_date").hide();
        $("#not_repetitive_date").show();
      }
    });
  

  });
</script>