config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :rooms do
    get 'allocate_repetitive', to: 'rooms#allocate_repetitive'
    get 'allocate_non_repetitive', to: 'rooms#allocate_non_repetitive'
    post 'allocate/repetitive_event', to: 'rooms#allocate_repetitive_event'
    post 'allocate/non_repetitive_event', to: 'rooms#allocate_non_repetitive_event'
  end

  resources :events do
    get 'search', to: 'events#search', on: :collection
    get 'cancel', to: 'events#cancel', on: :member
  end
end

app/models/event.rb
class Event
  include Mongoid::Document

  belongs_to :semester
  belongs_to :room

  field :name, type: String
  field :responsible, type: String
  field :start_time, type: String
  field :end_time, type: String
  field :days, type: Array

  DAYS_OF_WEEK = {
    1 => 'Segunda', 2 => 'Terça',
    3 => 'Quarta', 4 => 'Quinta',
    5 => 'Sexta'
  }.freeze

  def print_days_of_week
    return unless respond_to? :days
    days_of_week = ''
    days.each do |day|
      days_of_week << DAYS_OF_WEEK[day.to_i] << ','
    end unless days.nil?
    days_of_week
  end

  def self.find_events(name, responsible)
    events = where({})
    events = events.where(name: /#{name}/i) unless name.to_s.empty?
    events = events.where(responsible: /#{responsible}/i) unless responsible.to_s.empty?
    events
  end
  
end

class RepetitiveEvent < Event
  include Mongoid::Document

end

class NonRepetitiveEvent < Event
  include Mongoid::Document
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def search
    @events = Event.find_events(params[:name], params[:responsible])
  end

  def cancel
    event = Event.find params[:id]
    event.room.cancel_event(event)
    event.delete
    flash[:notice] = 'Evento cancelado'
    render :index
  end
end

app/views/events/index.html.erb
<center>
  <br>
  <%= image_tag("classroom.png", :alt => "classroom") %>
  <h2>Alocador de salas</h2>
</center>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <h3><i class="fa fa-search"></i> Pesquisar eventos </h3>
    <hr>
    <%= form_tag search_events_path, :method => "get" do %>

      <br>

      <div class="row">
        <div class="col-md-6">
          <%= label_tag(:name, "Nome do evento") %>
          <%= text_field_tag(:name, '', class: 'form-control') %>
        </div>
        <div class="col-md-6">
          <%= label_tag(:responsible, "Responsável pela sala") %>
          <%= text_field_tag(:responsible, '', {class: 'form-control'}) %>
        </div>
      </div>

      <br>
      <br>
      <div class="row">
        <div class="col-md-12">
          <div id="search_event_btn" >
            <%= submit_tag "Buscar eventos", class: "btn btn-primary btn-lg btn-block"%>
          </div>
        </div>
      </div>

  <% end %>
  </div>
</div>
<br>

app/views/events/search.html.erb
<h3><i class="fa fa-list"></i> Eventos encontrados: </h3>
<br>
<div class="row">
  <% @events.each do |event| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><h4 class="text-center"><%= event.name %></h4></div>
        <div class="panel-body">
          <p><b>Responsável:</b> <%= event.responsible %></p>
          <p><b>Hora de início:</b> <%= event.start_time %></p>
          <p><b>Hora de término:</b> <%= event.end_time %></p>
          <% if event.respond_to?(:days) && !event.days.nil? %>
            <p><b>Dias:</b> <%= event.print_days_of_week %></p>
          <% end %>
        </div>
        <div class="panel-footer">
          <%= link_to "Cancelar evento", cancel_event_path(event), class: 'btn btn-block btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
</div>