config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :rooms do
    get 'allocate_repetitive', to: 'rooms#allocate_repetitive'
    get 'allocate_non_repetitive', to: 'rooms#allocate_non_repetitive'
    post 'allocate/repetitive_event', to: 'rooms#allocate_repetitive_event'
    post 'allocate/non_repetitive_event', to: 'rooms#allocate_non_repetitive_event'
  end

  resources :events do
    get 'search', to: 'events#search', on: :collection
    get 'cancel', to: 'events#cancel', on: :member
  end
end

app/models/room.rb
class Room
  include Mongoid::Document

  has_and_belongs_to_many :equipments
  has_many :events

  field :capacity, type: Integer
  field :nickname, type: String
  field :identifier, type: String
  field :schedule, type: Hash

  REPETITIVE_ID = "2"

  def self.types
    Lab
    types = {}
    descendants.each do |type|
      types[type.name] = type::NAME if type.const_defined? 'NAME'
    end
    types
  end

  def self.find_availables(params)
    type = params[:room_type_class].constantize
    if(params[:capacity] != "" && params[:capacity] != nil)
      available_rooms = type.where(:capacity.gte => params[:capacity])
    else
      available_rooms = type.all()
    end

    start_time = params[:start_time].split(':')
    end_time = params[:end_time].split(':')
    if(params[:event_type_id] == self::REPETITIVE_ID)
      available_rooms = self.get_available_room_for_repetitive_event(params[:days_of_week], start_time, \
                        end_time, available_rooms)
    else
      available_rooms = self.get_available_room_for_not_repetitive_event(params[:days], start_time, end_time, available_rooms)
    end

    available_rooms
  end

  def self.get_available_room_for_repetitive_event(days_of_week, initial_hour, end_hour, available_rooms)
    rooms = []
    current_semester = Semester.current_semester
    hours = self.get_hours_range(initial_hour, end_hour)
    available_rooms.each do |available_room|
      can_add_room = true
      schedule = available_room.schedule
      if(schedule == nil)
        rooms.push(available_room)
      else
        schedule_for_semester = schedule[current_semester.id.to_s]
        if(schedule_for_semester != nil)
          schedule_for_semester.each do |event_datetime, event_id|
            date = Time.at(event_datetime.to_i).utc.to_datetime
            hour_on_date = date.strftime("%H")
            if(hours.include?(hour_on_date) && days_of_week.include?(date.cwday.to_s))
              can_add_room = false
              break
            end
          end

          if(can_add_room)
            rooms.push(available_room)
          end
        end
      end
    end
    rooms
  end

  def self.get_available_room_for_not_repetitive_event(days, initial_hour, end_hour, available_rooms)
    rooms = []
    current_semester = Semester.current_semester
    hours = self.get_hours_range(initial_hour, end_hour)
    available_rooms.each do |available_room|
      can_add_room = true
      schedule = available_room.schedule
      if(schedule == nil)
        rooms.push(available_room)
      else
        schedule_for_semester = schedule[current_semester.id.to_s]
        if(schedule_for_semester != nil)
          schedule_for_semester.each do |event_datetime, event_id|
            date = Time.at(event_datetime.to_i).utc.to_datetime
            hour_on_date = date.strftime("%H")
            date_to_test = date.strftime("%d/%m/%Y")
            if(hours.include?(hour_on_date) && days.include?(date_to_test))
              can_add_room = false
              break
            end
          end

          if(can_add_room)
            rooms.push(available_room)
          end
        end
      end
    end
    rooms
  end

  def self.get_hours_range(initial_hour, end_hour)
    hours = []
    (initial_hour[0].to_i..end_hour[0].to_i).each do |hour|
      hour_to_add = hour.to_s.size == 1 ? "0" + hour.to_s : hour.to_s
      hours.push(hour_to_add)
    end

    hours
  end

  def allocate(event)
    return unless respond_to?(:can_allocate?) && can_allocate?(event)
  end

  def can_allocate?(_event)
    true
  end

  def cancel_event(event, semester: nil)
    semester = semester.nil? ? Semester.current_semester : semester
    schedule[semester.id.to_s].each do |key, registered_event|
      schedule[semester.id.to_s].delete(key) if registered_event == event.id.to_s
    end
    save!
  end
end

class ClassRoom < Room
  include Mongoid::Document
end

class RegularClassRoom < ClassRoom
  include Mongoid::Document

  NAME = 'Sala de aula'.freeze
end

class SmartRoom < ClassRoom
  include Mongoid::Document

  NAME = 'Sala Inteligente'.freeze
end

class ConferenceRoom < ClassRoom
  include Mongoid::Document
end

class VideoConferenceRoom < ConferenceRoom
  include Mongoid::Document

  NAME = 'Sala de Vídeo Conferência'.freeze
end

class RegularConferenceRoom < ConferenceRoom
  include Mongoid::Document

  NAME = 'Sala de Conferência comum'.freeze
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @available_rooms = Room.find_availables(params)
  end

  def show
    @room = Room.find params[:id]
  end

  def allocate_repetitive
    @room = Room.find params[:room_id]
    @days_of_week = Event::DAYS_OF_WEEK
  end

  def allocate_non_repetitive
    @room = Room.find params[:room_id]
  end

  def allocate_non_repetitive_event
    Event
    room = Room.find params[:room_id]

    event_params = non_repetitive_event_params
    start_time = event_params[:start_time].split(':')
    end_time = event_params[:end_time].split(':')

    days = params[:days]
    days = days.split(",")

    semester = Semester.current_semester
    event = NonRepetitiveEvent.new event_params
    event.semester = semester
    event.room = room
    event.save!

    days.each do |day|
      (start_time[0].to_i..(end_time[0].to_i - 1)).each do |hour|
        time = day + " " + hour.to_s
        datetime = DateTime.strptime(time, "%d/%m/%Y %H")
        room.schedule = {} if room.schedule.nil?
        room.schedule[semester.id.to_s] = {} if room.schedule[semester.id.to_s].nil?
        room.schedule[semester.id.to_s][datetime.to_time.to_i] = event.id.to_s unless room.schedule.has_key?(datetime.to_time.to_i)
      end
    end

    room.save!

    flash[:notice] = "Evento alocado para sala #{room.identifier}!"
    render :index
  end

  def allocate_repetitive_event
    Event
    room = Room.find params[:room_id]

    event_params = repetitive_event_params
    start_time = event_params[:start_time].split(':')
    end_time = event_params[:end_time].split(':')
    days = params[:days]

    semester = Semester.current_semester
    event = RepetitiveEvent.new event_params
    event.semester = semester
    event.room = room
    event.save!

    (semester.start_date..semester.end_date).each do |date|
      if days.include?(date.cwday.to_s)
        (start_time[0].to_i..(end_time[0].to_i - 1)).each do |hour|
          datetime = DateTime.new(date.year, date.month, date.day, hour)
          room.schedule = {} if room.schedule.nil?
          room.schedule[semester.id.to_s] = {} if room.schedule[semester.id.to_s].nil?
          room.schedule[semester.id.to_s][datetime.to_time.to_i] = event.id.to_s unless room.schedule.has_key?(datetime.to_time.to_i)
        end
      end
    end
    room.save!

    Allocation.create! room: room, event: event

    flash[:notice] = "Evento alocado para sala #{room.identifier}!"
    render :index
  end

  def repetitive_event_params
    params.permit(:name, :responsible, :start_time, :end_time, days: [])
  end

  def non_repetitive_event_params
    params.permit(:name, :responsible, :start_time, :end_time, days: [])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/allocate_non_repetitive.html.erb
<h2 class="text-center">Alocação da sala <%= @room.identifier %> para evento não repetitivo</h2>

<h3><i class="fa fa-book"></i> Dados do evento
  <br>
  <small>Informe os dados do evento que ocorrerá nessa sala.</small>
</h3>
<br>

<%= form_tag room_allocate_non_repetitive_event_path, :method => "post" , id: "allocate-room-form" do %>

  <%= hidden_field_tag :event_type, "NonRepetitiveEvent" %>

  <div class="row">
    <div class="col-md-4">
      <%= label_tag(:name, "Nome do evento") %>
      <%= text_field_tag(:name, '', {class: 'form-control'}) %>
    </div>
    <div class="col-md-4">
      <%= label_tag(:responsible, "Responsável pela sala") %>
      <%= text_field_tag(:responsible, '', {class: 'form-control'}) %>
    </div>
  </div>

  <br>
  <h4><i class="fa fa-clock-o"></i> Período do evento
    <br>
    <small>Informe os dias da semana e os horários que ocorreram o evento.</small>
  </h4>
  <div class="row">
    <div class="col-md-4">
      <div id="not_repetitive_date">
        <input type='text' class="form-control" id='days' name="days"/>
      </div>
    </div>
    <div class="col-md-4">
      <div class="input-group bootstrap-timepicker timepicker">
        <input id="start_time" name="start_time" type="text" class="form-control input-small" placeholder="Hora inicial">
        <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="input-group bootstrap-timepicker timepicker">
        <input id="end_time" name="end_time" type="text" class="form-control input-small" placeholder="Hora final">
        <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
      </div>
    </div>
  </div>

  <br>
  <div class="row">
    <div class="col-md-12">
      <div id="new_event_btn" >
        <%= submit_tag "Novo evento para a sala #{@room.identifier}", class: "btn btn-primary btn-lg btn-block"%>
      </div>
    </div>
  </div>
<% end %>


<script type="text/javascript">
  $(document).ready(function(){
    var options = {
      maxHours: 24,
      showMeridian: false,
      minuteStep: 60,
      defaultTime: false,
      icons: {
        up: 'fa fa-chevron-up',
        down: 'fa fa-chevron-down'
      }
    };
    $('#start_time').timepicker(options);
    $('#end_time').timepicker(options);
    $('#days').datepicker({
      multidate: true,
      language: 'pt'
    });
  });
</script>

app/views/rooms/allocate_repetitive.html.erb
<h2 class="text-center">Alocação da sala <%= @room.identifier %> para evento repetitivo</h2>

<h3><i class="fa fa-book"></i> Dados do evento
  <br>
  <small>Informe os dados do evento que ocorrerá nessa sala.</small>
</h3>
<br>

<%= form_tag room_allocate_repetitive_event_path, :method => "post" , id: "allocate-room-form" do %>

  <%= hidden_field_tag :event_type, "RepetitiveEvent" %>

  <div class="row">
    <div class="col-md-4">
      <%= label_tag(:name, "Nome do evento") %>
      <%= text_field_tag(:name, '', {class: 'form-control'}) %>
    </div>
    <div class="col-md-4">
      <%= label_tag(:responsible, "Responsável pela sala") %>
      <%= text_field_tag(:responsible, '', {class: 'form-control'}) %>
    </div>
  </div>

  <br>
  <h4><i class="fa fa-clock-o"></i> Período do evento
    <br>
    <small>Informe os dias da semana e os horários que ocorreram o evento.</small>
  </h4>
  <div class="row">
    <div class="col-md-4">
      <div id="repetitive_date">
        <% @days_of_week.each do |num, day| %>
          <%= check_box_tag "days[]", num %>
          <%= day %>
        <% end%>
      </div>
    </div>
    <div class="col-md-4">
      <div class="input-group bootstrap-timepicker timepicker">
        <input id="start_time" name="start_time" type="text" class="form-control input-small" placeholder="Hora inicial">
        <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="input-group bootstrap-timepicker timepicker">
        <input id="end_time" name="end_time" type="text" class="form-control input-small" placeholder="Hora final">
        <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
      </div>
    </div>
  </div>

  <br>
  <div class="row">
    <div class="col-md-12">
      <div id="new_event_btn" >
        <%= submit_tag "Novo evento para a sala #{@room.identifier}", class: "btn btn-primary btn-lg btn-block"%>
      </div>
    </div>
  </div>
<% end %>


<script type="text/javascript">
  $(document).ready(function(){
    var options = {
      maxHours: 24,
      showMeridian: false,
      minuteStep: 60,
      defaultTime: false,
      icons: {
        up: 'fa fa-chevron-up',
        down: 'fa fa-chevron-down'
      }
    };
    $('#start_time').timepicker(options);
    $('#end_time').timepicker(options);
  });
</script>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-lg-2"></div>
  <div class="col-lg-6">
    <h3> Salas disponíveis </h3>
    <hr>
    <div class="list-group">
        <% if @available_rooms != nil && @available_rooms.size != 0 %>
    	   	<% @available_rooms.each do |available_room| %>
    	  		<%= link_to(
    		        available_room.nickname,
    		        room_path(available_room.id),
    		        {class: "list-group-item"}
    		    )%>
            <% end %>
      <% else %>
        <div class="alert alert-info">Não há salas disponíveis.</div>
	   	<% end %>
	</div>
  </div>
</div>

app/views/rooms/show.html.erb
<h2 class="text-center">Dados da sala <%= @room.identifier %></h2>

<b>Identificador da sala</b>: <%= @room.identifier || '-' %><br>
<b>Apelido da sala</b>: <%= @room.nickname || '-' %><br>
<b>Capacidade</b>: <%= @room.capacity || '-' %><br>

<h3>Eventos desta sala: </h3>
<div class="row">
  <% @room.events.each do |event| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><h4><%= event.name %></h4></div>
        <div class="panel-body">
          <p><b>Responsável:</b> <%= event.responsible %></p>
          <p><b>Hora de início:</b> <%= event.start_time %></p>
          <p><b>Hora de término:</b> <%= event.end_time %></p>
          <% if event.respond_to?(:days) && !event.days.nil? %>
            <p><b>Dias:</b> <%= event.print_days_of_week %></p>
          <% end %>
        </div>
        <div class="panel-footer">
          <%= link_to "Cancelar evento", cancel_event_path(event), class: 'btn btn-block btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>
<br>
<div class="row">
  <div class="col-md-3">
    <%=
      link_to(
        "Alocar sala para evento repetitivo",
        room_allocate_repetitive_path(@room),
        {class: "btn btn-lg"}
      )
    %>
  </div>
  <div class="col-md-3">
    <%if @room._type != "RegularConferenceRoom" %>
      <%=
        link_to(
          "Alocar sala para evento NÃO repetitivo",
          room_allocate_non_repetitive_path(@room),
          {class: "btn btn-lg"}
        )
      %>
    <% end %>
  </div>
</div>