config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :rooms do
    get 'allocate_repetitive', to: 'rooms#allocate_repetitive'
    get 'allocate_non_repetitive', to: 'rooms#allocate_non_repetitive'
    post 'allocate/repetitive_event', to: 'rooms#allocate_repetitive_event'
    post 'allocate/non_repetitive_event', to: 'rooms#allocate_non_repetitive_event'
  end

  resources :events do
    get 'search', to: 'events#search', on: :collection
    get 'cancel', to: 'events#cancel', on: :member
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnbRooms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <%= link_to "Unb Rooms", root_path, class: 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Pesquisar eventos", events_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid">
      <% flash.each do |name, msg| -%>
        <div class="alert alert-info">
          <%= msg %>
        </div>
      <% end -%>
      <br>
      <br>
      <%= yield %>
    </div>
  </body>
</html>